Repository StormSurgeLive/asgs, pull requests merged in 2021-05, with the labels that each got.

#467 review but do not merge Modified job properties to use single queue for small parallel jobs
  asgs_main.sh
Labels: bug, enhancement, in integration testing

#495 added latest scripts and documentation for generating cpra slide deck
  output/cpra_post.sh
  output/cpra_postproc/Automatic_Offset.csv
  output/cpra_postproc/FigureGenInputFiles/Default2.pal
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele.inp
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele_NAM.inp
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele_veerLeft100.inp
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele_veerLeft50.inp
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele_veerRight100.inp
  output/cpra_postproc/FigureGenInputFiles/FG51_SELA_maxele_veerRight50.inp
  output/cpra_postproc/FigureGenInputFiles/automate.sh
  output/cpra_postproc/FigureGenInputFiles/dofiguregen.py
  output/cpra_postproc/FigureGenInputFiles/inputlist.txt
  output/cpra_postproc/FigureGenInputFiles/tracklist.txt
  output/cpra_postproc/README.md
  output/cpra_postproc/SlideDeckGeneration-UserGuide.docx
  output/cpra_postproc/USGS_Service.m
  output/cpra_postproc/buildPPT.py
  output/cpra_postproc/cpra_hydrograph_plotter.m
  output/cpra_postproc/get_files_fortytwo_gahm.m
  output/cpra_postproc/parse22.sh
Labels: critical-path, enhancement

#500 New run.properties messaging for run properties database.
  asgs_main.sh
  config/2021/ncfs-dev/ncfs-dev-ec95d_nam.sh
  config/2021/ncfs-dev/ncfs-dev-hsofs_nam.sh
  init-asgs.sh
  monitoring/asgs-msgr.py
  monitoring/asgs-msgr.sh
  monitoring/logging.sh
  monitoring/rp2json.py
  output/transmit_rps.sh
Labels: enhancement
