Repository StormSurgeLive/asgs, pull requests merged in 2024-09, with the labels that each got.

#1369 Fixed build issues with edge length calculation
  util/input/nodalattr/convertna.f90
  util/input/nodalattr/submergence_eddyvis.f90
Labels: critical-path

#1387 Emergency update to v56 beta 2 patch for Frontera.
  bin/repost-all
  patches/ADCIRC/v56.0.0-beta.2/01-cmplrflags-mk.patch
Labels: adcirc build support

#1382 Made some operator UX improvements, around configs and asgs-mon.
  bin/build
  bin/fetch
  cloud/general/DOT-asgs-brew.sh
  cloud/general/init-jq.sh
Labels: UX
